### ISSUE TITLE
时间线只能选到2009年，能否支持手动填写

### ISSUE THREAD

**Issue by shuimu98** [ecmadao/hacknical#100]
比如，2007年入学，但是时间线只能拉到2009年，能否支持手动输入时间，或者时间线范围改大一些.

**Comment by ecmadao** [comment]
@shuimu98 感谢反馈，之前倒是没想到有那么早的..🌚 我先把时间拉长一点吧

**Comment by jkpang** [comment]
@ecmadao 🌚
![image](https://user-images.githubusercontent.com/17583451/52928944-2408dd00-337d-11e9-9446-67d01fb18d8f.png)

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>
