### ISSUE TITLE
登录失败，http 404

### ISSUE THREAD

**Issue by TinkoLiu** [ecmadao/hacknical#101]
登录也失效了（咦？

**Comment by ecmadao** [comment]
咦🌚
非常感谢反馈！ @TinkoLiu

**Comment by ecmadao** [comment]
@TinkoLiu 
已修复，非常感谢！改了个接口，忘记在 GitHub 后台改 OAuth 回调地址了..

**Comment by TinkoLiu** [comment]
感谢（其实是自己考研可能差不多凉了准备做简历结果发现登不进去hhhhhh

**Comment by ecmadao** [comment]
加油，祝好运~
