### ISSUE TITLE
How can I delete all my data from hacknical?

### ISSUE THREAD

**Issue by mrtnpro** [ecmadao/hacknical#103]
I see I can log out, however, how can I delete all data that hacknical has saved from my GH?

**Comment by ecmadao** [comment]
@mrtnpro 
Sorry, I don't support this feature right now. But if you want, just tell me directly and I'll do it for you. Besides, I hope you can tell me the reason why you wanna delete them, and some advice about hacknical. Thanks.

PS: These GitHub data I got from you is public, which means anybody can get it on GitHub without your access.

**Comment by mrtnpro** [comment]
@ecmadao Thanks, I'd appreciate if you could remove my data. I prefer to clean up after myself once I'm done using a service. That said, I simply wanted to have a look at how my Github data looks accumulated :) Other than that I have no use for hacknical (for now). However, it's a great tool you've built there. I'm sure it will come in handy for a lot of people.

**Comment by ecmadao** [comment]
@mrtnpro 
Okay. Done. Thanks for your feedback.
