### ISSUE TITLE
Code Course  和 Commits Review  无法正常显示

### ISSUE THREAD

**Issue by HuangStomach** [ecmadao/hacknical#105]
经常不显示 很久才会显示一下

**Comment by ecmadao** [comment]
@HuangStomach 
感谢反馈，我发现 GitHub `/repos/:owner/:repo/stats/commit_activity` 这个 API 真是太不稳定了...我节后想办法替换掉这个 API 吧

**Comment by HuangStomach** [comment]
另外生成PDF简历中 **查看%s的 GitHub 总结报告** 的链接好像有一些不对
会指向
`https://hacknical.com/resume/hacknical.com/{githubName}/github?locale=zh`
前面多追加了 `hacknical.com/resume` 直接就 404 了……

**Comment by ecmadao** [comment]
已修复，非常感谢反馈！

[cid:00BDC52ED61345D785962E4E951EE098]
在 2019年4月4日 +0800 22:50，HuangJP <notifications@github.com>，写道：

另外生成PDF简历中 查看%s的 GitHub 总结报告 的链接好像有一些不对
会指向
https://hacknical.com/resume/hacknical.com/{githubName}/github?locale=zh
前面多追加了 hacknical.com/resume 直接就 404 了……
