### ISSUE TITLE
[更新数据] 更新数据按钮无法点击了

### ISSUE THREAD

**Issue by CrazyBunQnQ** [ecmadao/hacknical#107]
更新数据按钮无法点击了， 请问还在维护嘛？

**Comment by yinxin630** [comment]
+1, 最近更新时间: 5 months ago, 无法点击更新

**Comment by ecmadao** [comment]
抱歉好久没看 GitHub。。我去检查下问题

**Comment by ecmadao** [comment]
消息队列居然欠费了，所以数据更新任务一直阻塞，是在抱歉🌚现已修复，退出后重新登录就能自动开始数据更新 @CrazyBunQnQ @yinxin630
