### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by imba-tjd** [ecmadao/hacknical#109]
* 参与贡献的仓库显示不出来

![图片](https://user-images.githubusercontent.com/24759802/64083756-f0106a80-cd56-11e9-8abb-22811892b93a.png)

![图片](https://user-images.githubusercontent.com/24759802/64083903-0e2a9a80-cd58-11e9-9e54-c79bc080062d.png)

* Firefox这个地方出现了滚动条

![图片](https://user-images.githubusercontent.com/24759802/64083776-2c43cb00-cd57-11e9-8781-76e1352cef38.png)

**Comment by ecmadao** [comment]
@imba-tjd 感谢反馈，不好意思才看见，大概修复了下
