### ISSUE TITLE
保存过的数据时常丢失

### ISSUE THREAD

**Issue by pcdotfan** [ecmadao/hacknical#113]
环境：macOS Catalina 10.15.2 / Chrome 79.0.3945.117

复现过程：

 - 选择英文简历
 - 填写任意字段，尤其是描述类型字段（project desc 此类）点击保存后 Preview 没有更新，刷新页面后数据丢失

**Comment by pcdotfan** [comment]
实在抱歉，原来是最后一条字段需要回车后才会被记录

**Comment by ecmadao** [comment]
@pcdotfan 感谢反馈😂说明页面上的指引也不够，我之后会想办法再优化一下
