### ISSUE TITLE
Resume is erased?

### ISSUE THREAD

**Issue by joeflack4** [ecmadao/hacknical#115]
Hello there~

Did something happen to your database?

This is my resume from last May:
[CV, Joe Flack.pdf](https://github.com/ecmadao/hacknical/files/4162539/CV.Joe.Flack.pdf)

But today, I logged in and I do not see my resume:
<img width="1119" alt="Screen Shot 2020-02-05 at 6 43 12 PM" src="https://user-images.githubusercontent.com/13045020/73893361-630e9780-4847-11ea-8572-6176069a89ed.png">

**Comment by ecmadao** [comment]
@joeflack4 
Sorry for that. It caused by wrong query for resume language. Fixed.
Thanks for feedback!

**Comment by joeflack4** [comment]
Haha. Awesome. Thank you!
