### ISSUE TITLE
更新数据提示成功, 但数据并没有更新

### ISSUE THREAD

**Issue by yinxin630** [ecmadao/hacknical#116]
RT

**Comment by ecmadao** [comment]
@yinxin630 
感谢反馈.. 最近没怎么看通知现在才发现 issue
前段时间我阿里云有欠费🌚应该是那个导致的数据抓取任务没能正常执行。现在应该是正常的，还请再手动刷新（或者重新登录）来触发一下数据更新任务？

**Comment by yinxin630** [comment]
嗯嗯, 试了下没问题了, 感谢 😄
