### ISSUE TITLE
If the resume is long the pages are croped

### ISSUE THREAD

**Issue by RNogales94** [ecmadao/hacknical#118]
This is a problem creating the resume template when it has more than one page

![image](https://user-images.githubusercontent.com/6784042/84491886-8c33ae80-aca5-11ea-8b6c-1f33b6f6464f.png)

**Comment by ecmadao** [comment]
Thanks for your feedback! Seems I can provide an option when download the resume: A whole page or clipped page. I'll update later in today.

**Comment by ecmadao** [comment]
Feature added. Now you can select the page style for your download.
![image](https://user-images.githubusercontent.com/10706318/85224343-4b9e0880-b3fc-11ea-81b6-ce701d35aa26.png)
