### ISSUE TITLE
[Rendering bug] You cannot have two jobs "Until now"

### ISSUE THREAD

**Issue by RNogales94** [ecmadao/hacknical#119]
In fact, it's possible to select it using the sliders. 

Furthermore in the preview it works:

(Look only to the dates, I have cropped the resume, but there were long lines)
![image](https://user-images.githubusercontent.com/6784042/86017889-e6ae6800-ba24-11ea-875b-08c3bc9069c9.png)

But it fails when you download it (using both options, one page or clipped pages)

This is what is finally rendered:

(Again, look only to the dates, I have cropped the resume, but there were long lines)
![image](https://user-images.githubusercontent.com/6784042/86018254-5d4b6580-ba25-11ea-8f37-e5e3fdde8f96.png)

If you need more details just ask me and I would provide them.

Thanks for your awesome tool

**Comment by RNogales94** [comment]
I have play a little bit, trying to solve it by myself.

![image](https://user-images.githubusercontent.com/6784042/86020800-a7821600-ba28-11ea-9bdb-b4f1734a4ce6.png)

It seems that the component works fine, but there is a bug "saving" the actual resume, the preview is always working fine, but after change something in jobs, no matter if text or dates, the change is correctly reflected in the preview.
However when you download the file, the change is not there.

**Comment by ecmadao** [comment]
Seems make sense. For now you need to save changes first when click download. If necessary, I can make it as auto-save when downloading. And for "for now" issue, I'll check it later this week ASAP. A little busy, sorry.

And thanks for your feedback!

**Comment by RNogales94** [comment]
I think it's not related with the saving itself, but with the rendering.

Even after click "save" and come back few days later the behaviour is this:

1) You click "save"
2) You click "preview"...

What you see:
![image](https://user-images.githubusercontent.com/6784042/86581085-e1e73800-bf7f-11ea-836a-4cd7bf82efa9.png)

(Both last positions are "until now" ---> Correct)

3) You click "download"...

What you get:

![image](https://user-images.githubusercontent.com/6784042/86581218-1bb83e80-bf80-11ea-949d-ca838682ec03.png)

Previous position now is not "until now" but "until last new date" maybe it is due to some internal logic that is avoiding "dates overlapping" (?)

Sorry, I cannot help with the code too much.. I'm backend / AI developer mostly, i have read your code and try to fix it but I have not enough React knowledge yet
