### ISSUE TITLE
Bug: hacknical.com: New updates not in downloaded resume

### ISSUE THREAD

**Issue by joeflack4** [ecmadao/hacknical#134]
## Expected behavior
After changing my work experience (adding a new job, projects, and information about them) and clicking "Save", downloading the resume as PDF should show my new additions.

## Actual behavior
No new additions appear. Instead, the downloaded resume looks the same as it was 6+ months ago, which was the last time I made changes to my resume.

## Steps to reproduce
1. Have an existing resume at hacknical.com
2. Go to "work experience", add a new job, and full it out fully. This involves (i) setting the date on the last job before this one to an actual month, instead of "until now", (ii) adding a new job, (iii) setting date range for that job, (iv) Adding projects, (v) filling out information in bullet points for those projects.
3. Click "Save" and wait for the success message to appear.
4. Click the "download" button and download either full page or multi-page PDF.
5. Open the PDF and observe that the new changes do not appear.

**Comment by ecmadao** [comment]
Quite strange...I used to think this because you forget to save, but seems not based on your description. Is it still not working?

**Comment by joeflack4** [comment]
Yeah, it's still an issue:

Saving the resume:
<img width="1160" alt="Screen Shot 2022-01-30 at 4 37 53 PM" src="https://user-images.githubusercontent.com/13045020/151719111-3235068d-329a-4869-96fb-83490f80bb85.png">
<img width="1238" alt="Screen Shot 2022-01-30 at 4 38 02 PM" src="https://user-images.githubusercontent.com/13045020/151719113-c97699cb-b26b-4cf9-b80a-5969b5b911a2.png">
<img width="962" alt="Screen Shot 2022-01-30 at 4 38 13 PM" src="https://user-images.githubusercontent.com/13045020/151719114-c57d9c89-689c-4735-834a-d26c0ea61886.png">

Result (can see my newest job does not appear):
[Joe Flack-resume-hacknical.pdf](https://github.com/ecmadao/hacknical/files/7966988/Joe.Flack-resume-hacknical.pdf)

Nice cat, by the way.

**Comment by ecmadao** [comment]
@joeflack4 Sorry to reply late. Fixed a bug right now, we can download the newest resume now.

**Comment by joeflack4** [comment]
@ecmadao It works! You're awesome, man, thank you. I was tempted to look into this myself, but it'd probably take me a long time. It looks like `locale` appears to have been an important param.

**Comment by ecmadao** [comment]
Right, cause I support create different resumes in different languages.
The bug is because the missing local parameter let the resume service returns a wrong resume 🤦
