### ISSUE TITLE
可移除选项

### ISSUE THREAD

**Issue by g-smaller** [ecmadao/hacknical#36]
每个参与的项目或者个人项目是否考虑加上移除状态

**Comment by ecmadao** [comment]
@g-smaller 
对，有考虑。
后期打算让分享页面的各个模块都可配置化，不过会先从大的模块入手，比如 repos、languages、commits，之后会细分到是否展示各个 repository 上

**Comment by g-smaller** [comment]
能否考虑下对没有个人项目的开发人员新增一个模块，让他们填写自己擅长的技术说明。

**Comment by ecmadao** [comment]
@g-smaller 
这个之前倒没有想过。。不过如果只是填写自己擅长的技术说明，可以放到最后个人说明那个模块里面？或者还有什么其他的建议吗？

**Comment by g-smaller** [comment]
有建议我会随时给你提；并且把它推荐给身边的朋友；

**Comment by ecmadao** [comment]
@g-smaller 
好嘞谢谢支持！
