### ISSUE TITLE
信息加载不出来?

### ISSUE THREAD

**Issue by xrr2016** [ecmadao/hacknical#44]
除了基本信息, 其他的信息都加载不出来...

**Comment by ecmadao** [comment]
@xrr2016 
好的收到，刚刚看了下，应该是第一次抓取超时了（这个服务器还是不靠谱，太慢了，之后打算搬回国内），然后抓取结果还被 redis 缓存了。我晚上回家后修复一下吧，今天白天加班😂

**Comment by xrr2016** [comment]
明白了, 周日也加班啊...
看到你的contributions, 简直可怕啊!

**Comment by ecmadao** [comment]
@xrr2016 
修复好了。。是数据缺失造成了前端没有渲染出来。非常感谢反馈！
好想发微信上捂脸那个表情啊。。🌚
