### ISSUE TITLE
/github/refresh, 同步接口失效

### ISSUE THREAD

**Issue by axetroy** [ecmadao/hacknical#48]
这个接口已经失效好几天了.
没法同步github的数据

**Comment by ecmadao** [comment]
@axetroy 
好的收到，谢谢反馈。这会儿在火车上。。🌚等明天晚上就排查下

**Comment by ecmadao** [comment]
@axetroy 
bug 已修复，再次感谢反馈

**Comment by axetroy** [comment]
应该的. 还没部署到线上是吧

**Comment by ecmadao** [comment]
@axetroy 
已经部署了，还是不行吗？

**Comment by axetroy** [comment]
不行, 返回504超时.

**Comment by ecmadao** [comment]
@axetroy 
并发太高了，我晚上回去处理一下

**Comment by ecmadao** [comment]
@axetroy 
改了接口，修复了下，你再在线上尝试一下吧？我这边测试 ok 了

**Comment by axetroy** [comment]
@ecmadao 
同步数据是可以了, 但是组织的贡献信息又抓取不对了,全都是贡献比例0.00%

**Comment by ecmadao** [comment]
@axetroy 
组织信息有了，不过感觉 organization 的数据抓取还不是很稳定，一次抓取的数据量太大了
