### ISSUE TITLE
简历中新增项目描述保存不了; 很期待简历导出的功能!

### ISSUE THREAD

**Issue by jkpang** [ecmadao/hacknical#50]
1. 简历 ->工作经历 ->参与项目->新增项目描述 保存不了;
2.很期待简历导出的功能!

**Comment by ecmadao** [comment]
@jkpang 
非常感谢反馈，经过检查发现是抽离组件依赖到 [light-ui](https://github.com/ecmadao/light-ui) 的过程中发生的 bug，现已修复并部署。

**Comment by jkpang** [comment]
您好,刚刚试用了一下 "新增项目描述"还是保存不了, 我重新清理了浏览器缓存/更换其他浏览器也是同样的结果. 麻烦了. @ecmadao

**Comment by ecmadao** [comment]
@jkpang 
我这边测试没问题，所以可以把问题描述的更具体一些吗？
![](http://obpykithy.bkt.clouddn.com/hacknical/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-03-23%20%E4%B8%8A%E5%8D%8812.28.14.png)
话说在 "新增项目描述" 的 input 里输入文字之后，是需要按下回车才能添加一行的，然后通过 `cmd + s` 或者 “保存” 按钮进行存储

**Comment by jkpang** [comment]
是我写了描述之后没有按回车键就直接保存了. 是我的错, 非常感谢您对开源社区的贡献! @ecmadao

**Comment by ecmadao** [comment]
@jkpang 
没事儿，也是我引导的不够好，之后会再完善一下

**Comment by ecmadao** [comment]
@jkpang
简历导出为 PDF 的功能（V1）已上线，不过做的比较仓促，欢迎试用并反馈～

**Comment by jkpang** [comment]
哇，厉害👍🏻！今晚回家试试看！

jkpang

2017年3月25日 +0800 12:13 ecmadao <notifications@github.com>，写道：

@jkpang<https://github.com/jkpang>
简历导出为 PDF 的功能（V1）已上线，不过做的比较仓促，欢迎试用并反馈～
