### ISSUE TITLE
关于组织信息的展示问题

### ISSUE THREAD

**Issue by yangyang0507** [ecmadao/hacknical#63]
<img width="823" alt="wx20170505-115523 2x" src="https://cloud.githubusercontent.com/assets/5666807/25733242/d0b6904e-3189-11e7-8276-a816aae27178.png">

https://github.com/baomidou/mybatis-plus-doc/commits/master

为什么这个repo没能准确展示出我的贡献值？

**Comment by ecmadao** [comment]
组织信息的数据抓取确实还有些问题的，已排在之后优化的计划表里

**Comment by yangyang0507** [comment]
👌
感谢作者！这是个非常牛逼的项目！
