### ISSUE TITLE
入职时间终点一直定位当前时间

### ISSUE THREAD

**Issue by chunge16** [ecmadao/hacknical#65]
入职时间终点无法准确定位

**Comment by ecmadao** [comment]
@chunge16 
你是指离职时间吗？

**Comment by ecmadao** [comment]
@chunge16 
之前因为设定的原因，离职时间如果拖拽到最后（即当月），则会被 format 为“至今”。所以如果是当月离职的话会被强制显示为至今在职，所以确实会有问题。现在这个问题刚刚已修复：拖拽到最后仍然会显示“至今”，但是离职时间可以选择到当前月份了。
