### ISSUE TITLE
填写简历一直出现禁止图标不让填写内容

### ISSUE THREAD

**Issue by Liuhui11** [ecmadao/hacknical#66]

**Comment by ecmadao** [comment]
@Liuhui11 
非常非常感谢反馈！太久没有测试第一次创建简历的流程了，刚刚试了下确实有问题，已修复，正在部署

**Comment by ecmadao** [comment]
@Liuhui11 
部署完成，你可以刷新页面试试。再次感谢反馈！

**Comment by Liuhui11** [comment]
@感谢，简历已经写好了，哈哈

**Comment by Liuhui11** [comment]
@ecmadao 我这边下载不了简历呢

**Comment by ecmadao** [comment]
填好以后有保存吗？如果没有保存的话也就没法下载 @Liuhui11

**Comment by Liuhui11** [comment]
点击保存感觉没有什么反应，下载按钮一直禁用

**Comment by ecmadao** [comment]
@Liuhui11 好像知道问题所在了。现在要下载的话可能还需要你先刷新一下页面，然后再点击下载试试（如果保存过了的话）。
不过我还得去修复一下🌚

**Comment by Liuhui11** [comment]
@ecmadao 刷新之后内容都没有了，我还是等你修复吧

**Comment by ecmadao** [comment]
哈哈哈好的😂，实在不好意思，我这会儿去查一下 @Liuhui11

**Comment by ecmadao** [comment]
@Liuhui11 
但是如果你刷新之后没有了内容，所以刚刚并没有保存填写的简历？通过点击那个绿色的“保存”按钮来保存，成功之后会有消息提示的。

**Comment by Liuhui11** [comment]
我点保存一直是没有反应看不出是成功还是失败了

**Comment by ecmadao** [comment]
好的了解了，感谢反馈。我去查下 log

**Comment by ecmadao** [comment]
@Liuhui11 
已修复且部署，万分抱歉。非常非常感谢你帮我找到好几个 bug 😆
你可以先随便填写一下简历，然后使用下载试试看，以免还有其他问题 🌚
