### ISSUE TITLE
生成的简历无法下载

### ISSUE THREAD

**Issue by dechinkey** [ecmadao/hacknical#68]
生成的简历无法下载，上方进度条刷新完成后无动作

**Comment by ecmadao** [comment]
@dechinkey 
hi 你好，简历无法下载的 bug 已修复。前一阵子迁移服务器的时候忘了改一些东西了。。非常感谢使用这个网站，我只希望自己做的东西能带来价值就很满意了。如果之后有什么想法或者建议，随时欢迎邮件或者 issue 沟通~
