### ISSUE TITLE
请问有没有可能开放 API 数据？

### ISSUE THREAD

**Issue by Desgard** [ecmadao/hacknical#79]
Hello 我是 GitHub 三方客户端 [Sepicat](https://itunes.apple.com/us/app/sepicat-for-github/id1355383210?mt=8) 作者，一直觉得 hacknical 对于 GitHub 上的数据分析很赞。请问作者有没有开放 API 的想法，我打算移植到移动端来做 native 的体验。

**Comment by ecmadao** [comment]
@Desgard 
可以开放的。目前 hacknical 主要分为三个部分，hacknical，hacknical-github，以及 github-crawler。hacknical 调用 hacknical-github 的 API 获取 GitHub 数据，而 hacknical-github 通过消息队列和 github-crawler 交互，去请求数据的更新。在 hacknical-github 这一层我做了权限验证，当初也准备在未来开放成为一个通用的 API 平台，而目前 hacknical 就算是它的一个应用了

**Comment by Desgard** [comment]
@ecmadao OK 期待 hacknical API 我会持续关注的
