### ISSUE TITLE
github总结报告中的编码历程显示不正确

### ISSUE THREAD

**Issue by yinxin630** [ecmadao/hacknical#85]
链接: https://hacknical.com/yinxin630/github?locale=zh

不知道跟我重写了项目 commit 历史有没有关系

**Comment by ecmadao** [comment]
OK Get. 具体哪个仓库，以及哪些地方有问题呢。是过去的 commit 没有展现出来吗？

**Comment by yinxin630** [comment]
![image](https://user-images.githubusercontent.com/6939365/43727802-935f0b3a-99d5-11e8-957a-51ad984b1096.png)

现在这个断断续续的是正常的吗? 因为之前都是连续的块, 不知道是不是改了展示形式

**Comment by ecmadao** [comment]
好嘞了解了。这个是后面改过一次样式，如果 commit 的时间段不是连续的就会有中断。多天连续的 commit 则会拼在一起。

**Comment by yinxin630** [comment]
哦哦, 感觉没之前的看起来舒服
