### ISSUE TITLE
希望能增加自定义列的功能

### ISSUE THREAD

**Issue by csvwolf** [ecmadao/hacknical#86]
比如想填点对外活动啥的 0v0

**Comment by csvwolf** [comment]
@ecmadao 是的，里面可以自定义内容就好

**Comment by ecmadao** [comment]
@csvwolf 
OK 了解了，我先构思一下

**Comment by ecmadao** [comment]
#87 Feature 已加，可自定义模块，不过还比较简陋，后面打算再进一步细化一下，并支持自定义各模块的顺序。如果有 bug 或者建议还烦请多多反馈~ @csvwolf

**Comment by csvwolf** [comment]
@ecmadao 感谢 issue 先关了，之后如果遇到问题再反馈 =w=
