### ISSUE TITLE
¿Is it posible to use with Private Repos in Github?

### ISSUE THREAD

**Issue by i-cruz-ramirez** [ecmadao/hacknical#92]
Hi, this is so far the best project to make a Beatiful CV using my Github Repositories.

I have some doubts, 

- Is it posible to use it with my Private Repos in Github?
- Is there any way to use it with Github or Gitlab?

I'm thinking to move all my repos from Gitlab to Github private repos to achieve a better understanding of how much we are programming. This tool that you've created could be very useful for my development team.

**Comment by ecmadao** [comment]
@i-cruz-ramirez 
Thanks for your feedback! It's possible to use private repos data in technical, but if I doing so, I had to ask more permissions for users. So maybe I can add this feature as optional senior config.

Anyway, I'll thinking about it. Thanks!

**Comment by i-cruz-ramirez** [comment]
Thanks! Would be great to add do so for a near future.
