### ISSUE TITLE
希望能够在简历模板中加入“证件照”

### ISSUE THREAD

**Issue by JohnNiang** [ecmadao/hacknical#95]

**Comment by ecmadao** [comment]
@JohnNiang 
非常感谢反馈。不过 hacknical 主要面向的是开发者，就我的经历和感受而言，照片在简历中的重要性较低，因此暂时不会考虑加入照片上传。但还是谢谢你的建议，祝好~

**Comment by JohnNiang** [comment]
@ecmadao 虽然这种重要性较低，可这种需求确实存在，可能并不低，希望您能够再次考虑**提供**这样的功能，至少供您的用户**选择**是否上传并显示证件照。

(byw，您的这个简历模板看着真的非常舒服，期待您接下来的优化:heart_eyes:
