### ISSUE TITLE
编程语言块 界面问题

### ISSUE THREAD

**Issue by xiaotiandada** [ecmadao/hacknical#98]
图表显示可能有点问题。

![image](https://user-images.githubusercontent.com/24250627/51106472-d4d40780-1826-11e9-8667-922ef1ee3836.png)

**Comment by ecmadao** [comment]
@xiaotiandada  感谢反馈！
不过我一开始就是那么设计的🌚因为感觉左边如果卡片边缘隔开的话也不是很好看...暂时还没有去探索其他设计方式

**Comment by xiaotiandada** [comment]
🌚🌚🌚 等我什么能把你的项目跑起来了 我就去看看 能不能改改23333~
