### ISSUE TITLE
/archive 打开空白有报错

### ISSUE THREAD

**Issue by yatessss** [ecmadao/hacknical#99]
报错信息：

react.79949eb9096260d77ba8.dll.js:14 TypeError: This library (validator.js) validates strings only
    at r (dashboard.bundle.0ff44563ce4f6fbde6bb.js:28)
    at Object.i [as isURL] (dashboard.bundle.0ff44563ce4f6fbde6bb.js:5)
    at t.isUrl (dashboard.bundle.0ff44563ce4f6fbde6bb.js:35)
    at z (0.bundle.0ff44563ce4f6fbde6bb.js:12)
    at 0.bundle.0ff44563ce4f6fbde6bb.js:12
    at Array.map (<anonymous>)
    at t.value (0.bundle.0ff44563ce4f6fbde6bb.js:12)
    at 0.bundle.0ff44563ce4f6fbde6bb.js:12
    at Array.map (<anonymous>)
    at t.value (0.bundle.0ff44563ce4f6fbde6bb.js:12)
l @ react.79949eb9096260d77ba8.dll.js:14
u @ react.79949eb9096260d77ba8.dll.js:14
w @ react.79949eb9096260d77ba8.dll.js:14
O @ react.79949eb9096260d77ba8.dll.js:14
h @ react.79949eb9096260d77ba8.dll.js:14
p @ react.79949eb9096260d77ba8.dll.js:14
enqueueSetState @ react.79949eb9096260d77ba8.dll.js:14
o.setState @ react.79949eb9096260d77ba8.dll.js:14
s.onStateChange @ react.79949eb9096260d77ba8.dll.js:6
notify @ react.79949eb9096260d77ba8.dll.js:22
e.notifyNestedSubs @ react.79949eb9096260d77ba8.dll.js:22
s.onStateChange @ react.79949eb9096260d77ba8.dll.js:6
s @ react.79949eb9096260d77ba8.dll.js:6
(anonymous) @ react.79949eb9096260d77ba8.dll.js:22
(anonymous) @ react.79949eb9096260d77ba8.dll.js:22
dispatch @ react.79949eb9096260d77ba8.dll.js:22
(anonymous) @ 0.bundle.0ff44563ce4f6fbde6bb.js:1
Promise.then (async)
(anonymous) @ 0.bundle.0ff44563ce4f6fbde6bb.js:1
(anonymous) @ react.79949eb9096260d77ba8.dll.js:22
(anonymous) @ react.79949eb9096260d77ba8.dll.js:22
(anonymous) @ react.79949eb9096260d77ba8.dll.js:22
value @ 0.bundle.0ff44563ce4f6fbde6bb.js:19
commitLifeCycles @ react.79949eb9096260d77ba8.dll.js:14
t @ react.79949eb9096260d77ba8.dll.js:14
w @ react.79949eb9096260d77ba8.dll.js:14
O @ react.79949eb9096260d77ba8.dll.js:14
h @ react.79949eb9096260d77ba8.dll.js:14
p @ react.79949eb9096260d77ba8.dll.js:14
enqueueSetState @ react.79949eb9096260d77ba8.dll.js:14
o.setState @ react.79949eb9096260d77ba8.dll.js:14
(anonymous) @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:35
Promise.then (async)
value @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:35
mountClassInstance @ react.79949eb9096260d77ba8.dll.js:14
beginWork @ react.79949eb9096260d77ba8.dll.js:14
o @ react.79949eb9096260d77ba8.dll.js:14
i @ react.79949eb9096260d77ba8.dll.js:14
u @ react.79949eb9096260d77ba8.dll.js:14
w @ react.79949eb9096260d77ba8.dll.js:14
O @ react.79949eb9096260d77ba8.dll.js:14
h @ react.79949eb9096260d77ba8.dll.js:14
p @ react.79949eb9096260d77ba8.dll.js:14
enqueueSetState @ react.79949eb9096260d77ba8.dll.js:14
o.setState @ react.79949eb9096260d77ba8.dll.js:14
(anonymous) @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:35
Promise.then (async)
value @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:35
mountClassInstance @ react.79949eb9096260d77ba8.dll.js:14
beginWork @ react.79949eb9096260d77ba8.dll.js:14
o @ react.79949eb9096260d77ba8.dll.js:14
i @ react.79949eb9096260d77ba8.dll.js:14
u @ react.79949eb9096260d77ba8.dll.js:14
w @ react.79949eb9096260d77ba8.dll.js:14
O @ react.79949eb9096260d77ba8.dll.js:14
h @ react.79949eb9096260d77ba8.dll.js:14
p @ react.79949eb9096260d77ba8.dll.js:14
updateContainer @ react.79949eb9096260d77ba8.dll.js:14
(anonymous) @ react.79949eb9096260d77ba8.dll.js:14
unbatchedUpdates @ react.79949eb9096260d77ba8.dll.js:14
vn @ react.79949eb9096260d77ba8.dll.js:14
render @ react.79949eb9096260d77ba8.dll.js:22
g @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:5
(anonymous) @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
s @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
f @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
setTimeout (async)
(anonymous) @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
c @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
fireWith @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
fire @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
c @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
fireWith @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
ready @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
setTimeout (async)
(anonymous) @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
(anonymous) @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:18
802cdb4f0b591dfd1229 @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:18
t @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:2
(anonymous) @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
87ab485b9c2e6379fa18 @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
t @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:2
(anonymous) @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:35
c5a77679dc03366c3801 @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:35
t @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:2
8768806f75593f9f965f @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:28
t @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:2
3 @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:5
t @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:2
(anonymous) @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:2
(anonymous) @ dashboard.bundle.0ff44563ce4f6fbde6bb.js:2

**Comment by yatessss** [comment]
如打开 https://hacknical.com/yatessss/resume

**Comment by ecmadao** [comment]
@yatessss 非常感谢反馈！貌似你的账户创建的比较早，后来数据结构变的时候有点问题没有兼容。我今天修复一下

**Comment by ecmadao** [comment]
@yatessss 已修复，非常感谢反馈！

**Comment by yatessss** [comment]
@ecmadao  还有一个报错，在进入/archive后，切换至工作经历时报错了，报错：

react.2ab80fecfb21cb0c38ed.dll.js:14 TypeError: Cannot read property 'replace' of undefined
    at t.value (0.bundle.dd157b7d69bbf795402a.js:19)
    at l (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at beginWork (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at o (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at i (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at u (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at w (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at O (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at h (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at p (react.2ab80fecfb21cb0c38ed.dll.js:14)
l @ react.2ab80fecfb21cb0c38ed.dll.js:14
u @ react.2ab80fecfb21cb0c38ed.dll.js:14
w @ react.2ab80fecfb21cb0c38ed.dll.js:14
O @ react.2ab80fecfb21cb0c38ed.dll.js:14
h @ react.2ab80fecfb21cb0c38ed.dll.js:14
p @ react.2ab80fecfb21cb0c38ed.dll.js:14
enqueueSetState @ react.2ab80fecfb21cb0c38ed.dll.js:14
o.setState @ react.2ab80fecfb21cb0c38ed.dll.js:14
(anonymous) @ dashboard.bundle.dd157b7d69bbf795402a.js:35
Promise.then (async)
value @ dashboard.bundle.dd157b7d69bbf795402a.js:35
mountClassInstance @ react.2ab80fecfb21cb0c38ed.dll.js:14
beginWork @ react.2ab80fecfb21cb0c38ed.dll.js:14
o @ react.2ab80fecfb21cb0c38ed.dll.js:14
i @ react.2ab80fecfb21cb0c38ed.dll.js:14
u @ react.2ab80fecfb21cb0c38ed.dll.js:14
w @ react.2ab80fecfb21cb0c38ed.dll.js:14
O @ react.2ab80fecfb21cb0c38ed.dll.js:14
batchedUpdates @ react.2ab80fecfb21cb0c38ed.dll.js:14
J @ react.2ab80fecfb21cb0c38ed.dll.js:14
Re @ react.2ab80fecfb21cb0c38ed.dll.js:14
0.bundle.dd157b7d69bbf795402a.js:19 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at t.value (0.bundle.dd157b7d69bbf795402a.js:19)
    at l (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at beginWork (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at o (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at i (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at u (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at w (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at O (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at h (react.2ab80fecfb21cb0c38ed.dll.js:14)
    at p (react.2ab80fecfb21cb0c38ed.dll.js:14)

**Comment by ecmadao** [comment]
@yatessss 已修复，再次感谢~
